name: Daily Myanmar News Digest

on:
  schedule:
    - cron: '30 0 * * *'  # ミャンマー時間 7:00（UTC+6.5）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dateutil lxml

      - name: Install dependencies
        run: |
          pip install --upgrade google-genai
          pip install --upgrade google-api-core

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sentence-transformers==2.2.2 huggingface_hub==0.25.2
          rm -rf ~/.cache/huggingface
      - name: Run fetch script
        run: python fetch_articles.py

      - name: Run script
        run: python fetch_articles.py
